Array Creation and Operation

In [2]:
import numpy as np

In [8]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# identity matrix
arr = np.eye(3)

arr = np.zeros(9, dtype=float).reshape(3,3)
for i in range(3):
    arr[i,i] = 1
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
from matplotlib.pyplot import plot as plt

arr = np.random.standard_normal(30)

In [36]:
# random array 2d
arr = np.random.randint(0,100,15).reshape(3,5)

# original
print(arr)

print()

# transposed q
print(arr.T)

[[79 59 61 51 75]
 [82 42 44  7 37]
 [41 71 60 30  3]]

[[79 82 41]
 [59 42 71]
 [61 44 60]
 [51  7 30]
 [75 37  3]]
