In [1]:
import numpy as np

def fill_spiral(n):
    # Initialize the matrix and boundaries
    matrix = np.zeros((n, n), dtype=int)
    top, bottom = 0, n - 1
    left, right = 0, n - 1
    num = 1
    
    # Directions: right, down, left, up
    directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
    dir_index = 0  # Start with the 'right' direction
    x, y = 0, 0  # Starting position
    
    while top <= bottom and left <= right:
        if dir_index == 0:  # Fill from left to right
            for y in range(left, right + 1):
                matrix[top, y] = num
                num += 1
            top += 1
        elif dir_index == 1:  # Fill from top to bottom
            for x in range(top, bottom + 1):
                matrix[x, right] = num
                num += 1
            right -= 1
        elif dir_index == 2:  # Fill from right to left
            for y in range(right, left - 1, -1):
                matrix[bottom, y] = num
                num += 1
            bottom -= 1
        elif dir_index == 3:  # Fill from bottom to top
            for x in range(bottom, top - 1, -1):
                matrix[x, left] = num
                num += 1
            left += 1
        
        # Move to the next direction
        dir_index = (dir_index + 1) % 4
    
    return matrix

# Example usage:
n = 5
result = fill_spiral(n)
print(result)


[[ 1  2  3  4  5]
 [16 17 18 19  6]
 [15 24 25 20  7]
 [14 23 22 21  8]
 [13 12 11 10  9]]
